telegram:
  token: "YOUR_BOT_TOKEN"
  webhook_url: "https://your.domain/webhook"
  webhook_path: "/webhook"
  webhook_port: 8080
  webhook_address: "0.0.0.0"
  webhook_secret: "YOUR_WEBHOOK_SECRET"

timezone: "Europe/Kyiv"
locale_file: "./locale.yaml"

database:
  driver: "mysql+pymysql" # or "sqlite"
  sqlite:
    file_path: "./power_herald.db"
  mariadb:
    host: "localhost"
    port: 3306
    user: "power_herald"
    password: "power_herald"
    database: "power_herald"

admin:
  chat_ids: ["YOUR_ADMIN_CHAT_ID_1", "YOUR_ADMIN_CHAT_ID_2"]

probing:
  passive:
    enabled: true
    interval_seconds: 10
    timeout_seconds: 1
    probe_count: 3
  active:
    enabled: true
    address: "0.0.0.0"
    port: 8081
    endpoint: "/ping"
    timeout_seconds: 10
  processor:
    interval_seconds: 20

outages:
  source: "file"
  json_url: "https://raw.githubusercontent.com/Baskerville42/outage-data-ua/refs/heads/main/data/kyiv.json"
  json_file: "./assets/kyiv-test.json"
  delay_seconds: 1800
  schedule_send_time:
    today: "06:00" # Empty string, false, or comment out to disable sending today's outages notification
    tomorrow: "21:00" # Empty string, false, or comment out to disable sending tomorrow's outage notification
  gpvs:
    - name: "Kyiv GPV 37.1"
      id: "GPV37.1"

maintenance:
  default_enabled: false
  comment: "Scheduled maintenance"

logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
